In [ ]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\cemre\\Desktop\\Datasets\\Trans.csv")
df.head(10)

,Unnamed: 0,X1.Mar,AACS,AAGAB,AAK1,AAMP,AAR2,AARS1,AARS2,AASDH,...,ZSCAN30,ZSCAN32,ZSWIM6,ZSWIM8,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,KD1,0.566502,-0.399693,0.167625,-0.800987,0.702601,0.148853,0.037085,0.243377,0.320555,...,-0.262518,-0.205354,-0.523488,-0.037085,0.359842,0.205354,-0.610592,-0.460707,-0.726531,0.111459
1,KD2,-0.055643,1.586959,-0.037085,1.237070,1.366803,0.523488,1.415589,1.415589,0.167625,...,0.419855,0.092824,0.610592,1.277943,0.130133,1.160996,0.018539,0.379692,1.321069,0.679066
2,KD3,1.655957,0.995280,-0.130133,1.321069,-1.091106,-0.936176,-0.320555,-0.320555,1.026176,...,1.125364,-0.440189,1.026176,-0.800987,-0.655902,0.167625,1.586959,-0.936176,0.340133,0.262518
3,KD4,0.679066,-1.026176,-0.512887,0.000000,-0.610592,-0.750885,-0.655902,-0.750885,-0.880174,...,0.205354,-0.750885,-0.018539,-0.853185,-1.026176,0.301099,-0.379692,0.419855,-0.523488,-0.826804
4,KD5,-0.359842,1.198166,-0.419855,0.965306,0.880174,0.880174,1.058083,0.880174,-0.046362,...,2.068794,0.826804,-0.679066,1.026176,0.679066,1.655957,-0.167625,0.633085,1.467999,0.340133
5,KD6,2.260761,1.160996,1.467999,-0.148853,1.932023,0.738653,0.775693,1.125364,0.880174,...,0.726531,1.586959,1.824027,1.932023,0.440189,2.260761,1.932023,1.824027,0.726531,0.566502
6,KD7,-0.523488,0.566502,-0.369749,0.995280,0.826804,0.907819,0.301099,0.588404,0.281756,...,0.775693,0.379692,-1.160996,-0.320555,0.243377,0.481421,-0.775693,-0.502343,0.243377,0.633085
7,KD8,1.237070,1.366803,-0.544869,0.243377,0.018539,-0.702601,0.262518,0.000000,-0.800987,...,-0.726531,-0.566502,1.091106,1.237070,-1.160996,0.610592,0.633085,0.679066,0.907819,-0.679066
8,KD9,0.262518,0.205354,-0.262518,0.633085,-0.826804,-1.217388,-0.440189,-1.160996,-1.160996,...,-0.588404,-1.058083,0.320555,0.965306,-1.366803,0.018539,-0.544869,1.524783,0.399693,-1.198166
9,KD10,0.588404,0.853185,0.750885,0.399693,0.775693,0.481421,-0.148853,0.262518,0.655902,...,1.467999,1.467999,1.932023,1.321069,0.092824,1.277943,1.467999,2.068794,0.853185,0.130133

In [4]:
df.shape

(135, 7769)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Columns: 7769 entries, Unnamed: 0 to ZZZ3
dtypes: float64(7768), object(1)
memory usage: 8.0+ MB

In [6]:
df.isnull().sum()

Unnamed: 0    0
X1.Mar        0
AACS          0
AAGAB         0
AAK1          0
             ..
ZXDC          0
ZYG11B        0
ZYX           0
ZZEF1         0
ZZZ3          0
Length: 7769, dtype: int64

In [7]:
df.describe()

,X1.Mar,AACS,AAGAB,AAK1,AAMP,AAR2,AARS1,AARS2,AASDH,AASDHPPT,...,ZSCAN30,ZSCAN32,ZSWIM6,ZSWIM8,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
count,1.350000e+02,1.350000e+02,135.000000,1.350000e+02,135.000000,135.000000,1.350000e+02,1.350000e+02,1.350000e+02,1.350000e+02,...,1.350000e+02,1.350000e+02,1.350000e+02,1.350000e+02,1.350000e+02,135.000000,1.350000e+02,1.350000e+02,1.350000e+02,1.350000e+02
mean,-2.006625e-16,-2.236894e-16,0.000027,-1.981954e-16,0.000149,0.000551,-1.694118e-16,-1.834438e-16,9.839929e-07,-6.858249e-07,...,-1.891491e-16,-5.884735e-08,-1.771374e-08,-2.166991e-16,-2.055969e-16,0.000003,-2.368476e-16,-2.205026e-16,-2.228670e-16,-2.310909e-16
std,9.925155e-01,9.925155e-01,0.992448,9.925155e-01,0.992120,0.990911,9.925155e-01,9.925155e-01,9.925104e-01,9.925135e-01,...,9.925155e-01,9.925125e-01,9.925148e-01,9.925155e-01,9.925155e-01,0.992509,9.925155e-01,9.925155e-01,9.925155e-01,9.925155e-01
min,-2.612709e+00,-2.612709e+00,-2.612709,-2.612709e+00,-2.612709,-2.400372,-2.612709e+00,-2.612709e+00,-2.612709e+00,-2.612709e+00,...,-2.612709e+00,-2.612709e+00,-2.612709e+00,-2.612709e+00,-2.612709e+00,-2.612709,-2.612709e+00,-2.612709e+00,-2.612709e+00,-2.612709e+00
25%,-6.674844e-01,-6.674844e-01,-0.667484,-6.674844e-01,-0.667484,-0.667440,-6.674844e-01,-6.674844e-01,-6.674844e-01,-6.674844e-01,...,-6.674844e-01,-6.674844e-01,-6.674844e-01,-6.674844e-01,-6.674844e-01,-0.667484,-6.674844e-01,-6.674844e-01,-6.674844e-01,-6.674844e-01
50%,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-9.269207e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.674844e-01,6.674844e-01,0.667484,6.674844e-01,0.667484,0.667484,6.674844e-01,6.674844e-01,6.674844e-01,6.674844e-01,...,6.674844e-01,6.674844e-01,6.674844e-01,6.674844e-01,6.674844e-01,0.667484,6.674844e-01,6.674844e-01,6.674844e-01,6.674844e-01
max,2.612709e+00,2.612709e+00,2.612709,2.612709e+00,2.612709,2.612709,2.612709e+00,2.612709e+00,2.612709e+00,2.612709e+00,...,2.612709e+00,2.612709e+00,2.612709e+00,2.612709e+00,2.612709e+00,2.612709,2.612709e+00,2.612709e+00,2.612709e+00,2.612709e+00